version: '3.8'
services:
  client:
    build: .
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./dnd:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
    networks:
      - proxy
networks:
  proxy:
    external: true